/*
 * sme API
 *
 * this is sme Api doc
 *
 * API version: 2.0.0+2024-02-15
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type SignInUserDto[T SignInUserDtoCredentialData] struct {

	// The user source
	Source string `json:"source,omitempty"`

	CredentialData SignInUserDtoCredentialData `json:"credentialData,omitempty"`
}
