/*
 * sme API
 *
 * this is sme Api doc
 *
 * API version: 2.0.0+2024-02-15
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type SignInUserResponse struct {

	// User token in JWT format
	Token string `json:"token,omitempty"`
}
