/*
 * sme API
 *
 * this is sme Api doc
 *
 * API version: 2.0.0+2024-02-15
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package dto

type Wallet struct {

	// private key of the wallet
	PrivateKey string `json:"privateKey,omitempty"`

	// wallet address
	WalletAddress string `json:"walletAddress,omitempty"`
}
